SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Todo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[DateCreated] [datetime] NULL,
	[Complete] [bit] NOT NULL,
	[DateCompleted] [datetime] NULL,
	[UserId] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Todo] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Todo] ADD  DEFAULT ((0)) FOR [Complete]
GO
